/*
 *  Licensed to the Apache Software Foundation (ASF) under one or more
 *  contributor license agreements.  See the NOTICE file distributed with
 *  this work for additional information regarding copyright ownership.
 *  The ASF licenses this file to You under the Apache License, Version 2.0
 *  (the "License"); you may not use this file except in compliance with
 *  the License.  You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

plugins {
    id 'java'
    id 'distribution'
}

version = projectVersion
group = 'org.apache.grails'

ext {
    pomTitle = 'Grails Wrapper Downloader'
    pomDescription = 'Downloads necessary libraries for the Grails Wrapper'
    pomDevelopers = [
            'graemerocher'  : 'Graeme Rocher',
            'jeffscottbrown': 'Jeff Brown',
            'puneetbehl'    : 'Puneet Behl',
            'jdaugherty'    : 'James Daugherty'
    ]
    cliProject = true
    startMainClass = 'grails.init.Start'
}

// Intentionally no dependencies to prevent bloat

apply {
    from rootProject.layout.projectDirectory.file('gradle/java-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}

// It's surprisingly hard to generate start scripts and *not* have them nested into a bin / lib directory
// rather than defining the application and then having to add tasks to rework it, just define a distribution and
// create the scripts in the right location from the start
tasks.named('jar', Jar) {
    archiveFileName = "${name}.jar" as String
    manifest {
        attributes 'Main-Class': project.property('startMainClass')
    }
}

tasks.register('createStartScripts', CreateStartScripts) {
    outputDir = layout.buildDirectory.dir('generated-scripts').get().asFile
    applicationName = 'grailsw'
    mainClass = project.findProperty('startMainClass') as String
    classpath = files(tasks.named('jar'))

    // See gradle tickets such as for lib https://github.com/gradle/gradle/issues/7033
    doLast {
        unixScript.text = unixScript.text
                .replace('$APP_HOME/lib/', '$APP_HOME/')
                .replace('"${APP_HOME:-./}.."', '"${APP_HOME:-./}"')

        windowsScript.text = windowsScript.text
                .replace('%APP_HOME%\\lib\\', '%APP_HOME%\\')
                .replace('"%APP_HOME%\\lib\\', '"%APP_HOME%\\')
                .replace('%DIRNAME%..', '%DIRNAME%')
    }
}

extensions.getByType(DistributionContainer).configureEach {
    contents {
        from(tasks.named('jar')) {
            into('')
        }
        from('createStartScripts') {
            into('')
            filePermissions {
                unix(0755)
            }
        }
    }
}

tasks.named('assemble') {
    dependsOn('createStartScripts')
}
tasks.named('installDist') {
    dependsOn('createStartScripts')
}
tasks.named('distZip') {
    dependsOn('createStartScripts')
}
tasks.named('distTar') {
    dependsOn('createStartScripts')
}