/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package grails.gorm.annotation.multitenancy

import org.codehaus.groovy.ast.ASTNode
import org.codehaus.groovy.ast.ClassNode
import org.codehaus.groovy.ast.CodeVisitorSupport
import org.codehaus.groovy.ast.MethodNode
import org.codehaus.groovy.ast.ModuleNode
import org.codehaus.groovy.ast.expr.DeclarationExpression
import org.codehaus.groovy.control.CompilationUnit
import org.codehaus.groovy.control.MultipleCompilationErrorsException
import org.codehaus.groovy.control.Phases

import spock.lang.Specification

import org.grails.datastore.gorm.multitenancy.transform.TenantTransform

/**
 * {@link CurrentTenantTransformSpec} only exercises {@code @CurrentTenant} and
 * {@code @WithoutTenant}, which both take {@code TenantTransform#buildDelegatingMethodCall}'s first
 * two branches. The third branch - the actual {@code @Tenant} annotation, which resolves the tenant
 * id from a closure supplied as the annotation value - and its own error path (a non-closure value)
 * were unexercised. These specs cover that branch directly, plus the small standalone
 * {@code getAnnotationType()}/{@code hasTenantAnnotation} surface not reached by any existing spec.
 */
class TenantTransformSpec extends Specification {

    void "test @Tenant with a closure value transforms a method to resolve the tenant id from the closure"() {
        given: 'a service with @Tenant applied at the method level with a closure tenant resolver'
        MethodNode methodNode = compileAndFindMethod('''
import grails.gorm.multitenancy.Tenant

class BookService {
    @Tenant({ "someTenant" })
    List listBooks() {
        return ["The Stand"]
    }
}
''', 'BookService', 'listBooks')

        expect: 'a $tenantResolver local was declared from the closure, only generated by the closure-resolving branch'
        declaredVariableNames(methodNode.code).contains('$tenantResolver')
    }

    void "test @Tenant applied at the class level transforms every method the same way"() {
        given: 'a service with @Tenant applied at the class level with a closure tenant resolver'
        MethodNode methodNode = compileAndFindMethod('''
import grails.gorm.multitenancy.Tenant

@Tenant({ "someTenant" })
class BookService {
    List listBooks() {
        return ["The Stand"]
    }
}
''', 'BookService', 'listBooks')

        expect: 'a $tenantResolver local was declared from the closure, only generated by the closure-resolving branch'
        declaredVariableNames(methodNode.code).contains('$tenantResolver')
    }

    void "test @Tenant with a non-closure value fails to compile"() {
        when:
        new GroovyClassLoader().parseClass('''
import grails.gorm.multitenancy.Tenant

class BookService {
    @Tenant(String)
    List listBooks() {
        return ["The Stand"]
    }
}
''')

        then:
        MultipleCompilationErrorsException e = thrown()
        e.message.contains('@Tenant value should be a closure')
    }

    void "getAnnotationType returns the @Tenant annotation type"() {
        expect:
        new TenantTransform().getAnnotationType() == TenantTransform.TENANT_ANNOTATION_TYPE
    }

    void "hasTenantAnnotation returns false for a method annotated with @WithoutTenant even though the class is annotated with @CurrentTenant"() {
        given:
        MethodNode methodNode = compileAndFindMethod('''
import grails.gorm.multitenancy.CurrentTenant
import grails.gorm.multitenancy.WithoutTenant

@CurrentTenant
class BookService {
    @WithoutTenant
    List listBooks() {
        return []
    }
}
''', 'BookService', 'listBooks')

        expect:
        !TenantTransform.hasTenantAnnotation(methodNode)
    }

    void "hasTenantAnnotation returns true when called directly with a class node carrying @Tenant"() {
        given:
        ClassNode classNode = compileAndFindClass('''
import grails.gorm.multitenancy.Tenant

@Tenant({ "someTenant" })
class BookService {
    List listBooks() {
        return []
    }
}
''', 'BookService')

        expect:
        TenantTransform.hasTenantAnnotation(classNode)
    }

    void "hasTenantAnnotation returns false for a plain class node with no tenant annotations"() {
        given:
        ClassNode classNode = compileAndFindClass('''
class PlainService {
    List listBooks() {
        return []
    }
}
''', 'PlainService')

        expect:
        !TenantTransform.hasTenantAnnotation(classNode)
    }

    private static ClassNode compileAndFindClass(String source, String className) {
        CompilationUnit unit = new CompilationUnit(new GroovyClassLoader())
        def sourceUnit = unit.addSource('Source.groovy', source)
        unit.compile(Phases.CANONICALIZATION)
        ModuleNode moduleNode = sourceUnit.getAST()
        (ClassNode) moduleNode.classes.find { ClassNode cn -> cn.name == className }
    }

    private static MethodNode compileAndFindMethod(String source, String className, String methodName) {
        compileAndFindClass(source, className).methods.find { it.name == methodName }
    }

    private static List<String> declaredVariableNames(ASTNode node) {
        List<String> names = []
        def visitor = new CodeVisitorSupport() {
            @Override
            void visitDeclarationExpression(DeclarationExpression expression) {
                names << expression.leftExpression.text
                super.visitDeclarationExpression(expression)
            }
        }
        node.visit(visitor)
        names
    }
}
