/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package openapirest

import groovy.xml.XmlSlurper

import io.swagger.v3.core.util.Yaml31
import org.springframework.util.ClassUtils
import spock.lang.Shared
import spock.lang.Specification

import grails.testing.mixin.integration.Integration
import org.apache.grails.testing.http.client.HttpClientSupport

/**
 * Confirms the description the generate-open-api command writes for an application built the way a
 * generated REST application is - its controllers generated by the rest-api profile, its mappings
 * leaving the controller to the request, its responses rendered by JSON views, and no springdoc -
 * describes what the application answers.
 */
@Integration
class RestApiDocumentFunctionalSpec extends Specification implements HttpClientSupport {

    @Shared
    Map document = Yaml31.mapper().readValue(new File(System.getProperty('openapi.generated.directory'), 'openapi.yaml'), Map)

    void 'the description is generated without springdoc'() {
        expect:
        !ClassUtils.isPresent('org.springdoc.core.customizers.OpenApiCustomizer', getClass().classLoader)
        http('/v3/api-docs').assertStatus(404)
        document.openapi == '3.1.0'
    }

    void 'the controllers the mappings reach are described, at the paths they are reached at'() {
        expect: 'patch is mapped, but the controller has no patch action, so it is not described'
        operations(document) == ['get /book', 'post /book', 'get /book/{id}', 'put /book/{id}', 'delete /book/{id}',
                                 'get /'] as Set
    }

    void 'a book created as described answers as described'() {
        when:
        def created = httpPostJson('/book', '{"title":"Kindred","isbn":"9780807083697","pages":287}')

        then: 'with the status and shape described'
        created.assertStatus(201)
        conforms(created.json(), schema('Book'))
        described('post', '/book').responses.containsKey('201')
    }

    void 'a listing answers as described'() {
        given:
        httpPostJson('/book', '{"title":"Parable of the Sower","isbn":"9781538732182"}').assertStatus(201)

        when:
        List listed = http('/book').jsonList()

        then:
        described('get', '/book').responses['200'].content['application/json'].schema.items['$ref'] ==
                '#/components/schemas/Book'
        listed
        listed.every { Map book -> conforms(book, schema('Book')) }
    }

    void 'the identifier is described as the domain class declares it'() {
        expect:
        described('get', '/book/{id}').parameters.find { it.name == 'id' }.schema == [type: 'integer', format: 'int64']
    }

    void 'what data binding leaves out of a book is described as read only'() {
        given:
        Map<String, Map> book = (Map<String, Map>) schema('Book').get('properties')

        expect: 'the identifier Grails assigns, and not the properties a book is bound from'
        book.id.readOnly
        ['title', 'isbn', 'pages'].every { !book[it].readOnly }

        and: 'the version Grails does not render is not described'
        !book.containsKey('version')
    }

    void 'a failed validation answers with the errors the errors view renders, as described'() {
        given:
        Map errors = schema('ValidationErrors')
        Map one = (Map) errors.oneOf[0]
        Map several = (Map) errors.oneOf[1]

        when: 'a book with one invalid property, and one with several'
        Map single = httpPostJson('/book', '{"title":"Dawn"}').assertStatus(422).json()
        Map multiple = httpPostJson('/book', '{"title":"","isbn":"x"}').assertStatus(422).json()

        then:
        described('post', '/book').responses['422'].content['application/json'].schema['$ref'] ==
                '#/components/schemas/ValidationErrors'
        conforms(single, one)
        conforms(multiple, several)
        ((List<Map>) ((Map) multiple._embedded).errors).every { Map error -> conforms(error, one) }
    }

    void 'a failed validation in XML answers with the errors the converters render, as described'() {
        when:
        def response = httpPostJson([Accept: 'text/xml'], '/book', '{"title":"Dawn"}')
        def errors = new XmlSlurper().parseText(response.body())
        Map schema = (Map) ((Map) described('post', '/book').responses['422'].content['text/xml']).schema
        Map error = (Map) ((Map) ((Map) schema.get('properties')).errors).items

        then: 'the errors view renders only JSON, so the converters render the XML'
        response.assertStatus(422)
        errors.name() == schema.xml.name
        errors.children().every { it.name() == error.xml.name }

        and: 'naming the object and the field in its attributes'
        errors.error[0].@object.text()
        errors.error[0].@field.text() == 'isbn'
        ((Map) ((Map) error.get('properties')).field).xml.attribute
    }

    void 'a book answers in XML as described'() {
        given:
        Map created = httpPostJson('/book', '{"title":"Fledgling","isbn":"9780446696166"}').assertStatus(201).json()

        when:
        def book = new XmlSlurper().parseText(http([Accept: 'text/xml'], "/book/${created.id}").body())
        Map schema = schema('Book')

        then: 'an element named for the class, with the identifier as an attribute'
        book.name() == schema.xml.name
        book.@id.text() == created.id.toString()
        ((Map) ((Map) schema.get('properties')).id).xml.attribute

        and: 'its properties as elements'
        book.title.text() == 'Fledgling'
    }

    private Map described(String method, String path) {
        (Map) ((Map) document.paths[path])[method]
    }

    private Map schema(String name) {
        (Map) ((Map) document.components).schemas[name]
    }

    /**
     * A value conforms where it has every property the schema requires and none it does not describe.
     */
    private static boolean conforms(Map value, Map schema) {
        Set described = ((Map) schema.get('properties')).keySet()
        value.keySet().every { it in described } && ((schema.required ?: []) as List).every { value.containsKey(it) }
    }

    private static Set<String> operations(Map document) {
        document.paths.collectMany { String path, Map item -> item.keySet().collect { "${it} ${path}".toString() } } as Set<String>
    }
}
