/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
import org.apache.tools.ant.DirectoryScanner

pluginManagement {
    apply from: file('../gradle/plugin-repositories.gradle')
    repositories {
        configurePluginRepositories(delegate)
    }
}

plugins {
	id 'com.gradle.develocity' version '4.3.2'
	id 'com.gradle.common-custom-user-data-gradle-plugin' version '2.4.0'
}

def isCI = System.getenv().containsKey('CI')
def isLocal = !isCI
def isReproducibleBuild = System.getenv('SOURCE_DATE_EPOCH') != null
if (isReproducibleBuild) {
    gradle.settingsEvaluated {
        logger.warn('*************** Remote Build Cache Disabled due to Reproducible Build ********************')
        logger.warn("Build date will be set to (SOURCE_DATE_EPOCH=${System.getenv("SOURCE_DATE_EPOCH")})")
    }
}

develocity {
	server = 'https://develocity.apache.org'
	buildScan {
		publishing.onlyIf { it.authenticated }
		uploadInBackground = isLocal
	}
}

buildCache {
    local { enabled = (isLocal && !isReproducibleBuild) || (isCI && isReproducibleBuild) }
    remote(develocity.buildCache) {
        push = isCI
        enabled = !isReproducibleBuild
    }
}

dependencyResolutionManagement {
    repositories {
        if (System.getenv('GRAILS_INCLUDE_MAVEN_LOCAL')) {
            mavenLocal()
        }
        mavenCentral()
        gradlePluginPortal()
        // publish plugin
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex('org[.]apache[.]grails[.]gradle.*', '.*', '.*-SNAPSHOT')
            }
            mavenContent {
                snapshotsOnly()
            }
        }
        maven {
            url = 'https://repository.apache.org/content/groups/staging'
            content {
                includeModuleByRegex('org[.]apache[.]grails[.]gradle', 'grails-publish')
            }
            mavenContent {
                releasesOnly()
            }
        }
    }
}

rootProject.name = 'build-logic-root'

include 'build-logic'
project(':build-logic').projectDir = file('plugins')

include 'grails-docs-core'
project(':grails-docs-core').projectDir = file('docs-core')

// Due to https://github.com/gradle/gradle/issues/2986 , we can't change the global exclude for profiles, it must be done everywhere
for (String pattern in DirectoryScanner.defaultExcludes) {
    if (pattern.contains('gitignore') || pattern.contains('gitattributes')) {
        DirectoryScanner.removeDefaultExclude(pattern)
    }
}
