/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.grails.taglib.discovery;

/**
 * The properties of a method that decide whether it is a tag.
 *
 * <p>Tag discovery happens twice: over {@code java.lang.reflect.Method} when an application is
 * running, and over the abstract syntax tree while a tag library is compiled. The two must reach the
 * same answer — a method treated as a tag by one and not the other either fails to dispatch after
 * compiling cleanly, or is reported as unknown despite being callable.
 *
 * <p>This is the abstraction that lets {@link TagDiscoveryRules} be the only place those rules are
 * written, with a small adapter for each source of truth rather than a second implementation.
 *
 * @since 8.0.0
 */
public interface TagMethodView {

    /**
     * @return the method name
     */
    String getName();

    /**
     * @return true if the method is public
     */
    boolean isPublic();

    /**
     * @return true if the method is static
     */
    boolean isStatic();

    /**
     * @return true if the method was generated by the compiler rather than written, covering bridge
     *         methods and the accessors trait application produces
     */
    boolean isGenerated();

    /**
     * @return true if the method is annotated {@code @Tag}, which makes it a tag whatever its shape
     */
    boolean hasTagAnnotation();

    /**
     * @return true if the method is annotated {@code @NotATag}, which excludes it whatever its shape
     */
    boolean hasNotATagAnnotation();

    /**
     * @return the number of declared parameters
     */
    int getParameterCount();

    /**
     * @param index a parameter position
     * @return true if a {@link java.util.Map} may be passed for this parameter
     */
    boolean isParameterMapAssignable(int index);

    /**
     * @param index a parameter position
     * @return true if a {@link groovy.lang.Closure} may be passed for this parameter
     */
    boolean isParameterClosureAssignable(int index);

    /**
     * @param index a parameter position
     * @return the parameter's name, meaningful only when {@link #isParameterNamePresent(int)} is true
     */
    String getParameterName(int index);

    /**
     * @param index a parameter position
     * @return true if the compiled method retains parameter names, which decides whether a parameter
     *         has to be named {@code attrs} or {@code body} to be recognised as such
     */
    boolean isParameterNamePresent(int index);

    /**
     * @param index a parameter position
     * @return true if the parameter has a default value, so that Groovy will also generate overloads
     *         that omit it
     */
    boolean isParameterOptional(int index);
}
