/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

configurations.register('documentation') {
    canBeConsumed = false
    canBeResolved = true
    attributes {
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
        attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling, Bundling.EXTERNAL))
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
    }
}
dependencies {
    add('documentation', platform(project(':grails-gradle-bom')))
    add('documentation', 'org.fusesource.jansi:jansi')
    add('documentation', 'jline:jline')
    add('documentation', 'com.github.javaparser:javaparser-core')
/*
    Temporarily use 4.0.27-SNAPSHOT for documentation generation until 4.0.27 is released.
    add('documentation', "org.apache.groovy:groovy:${bomDependencyVersions['groovy.version']}")
    add('documentation', "org.apache.groovy:groovy-groovydoc:${bomDependencyVersions['groovy.version']}")
    add('documentation', "org.apache.groovy:groovy-ant:${bomDependencyVersions['groovy.version']}")
    add('documentation', "org.apache.groovy:groovy-docgenerator:${bomDependencyVersions['groovy.version']}")
    add('documentation', "org.apache.groovy:groovy-templates:${bomDependencyVersions['groovy.version']}")
*/
    add('documentation', 'org.apache.groovy:groovy:4.0.27-SNAPSHOT')
    add('documentation', 'org.apache.groovy:groovy-groovydoc:4.0.27-SNAPSHOT')
    add('documentation', 'org.apache.groovy:groovy-ant:4.0.27-SNAPSHOT')
    add('documentation', 'org.apache.groovy:groovy-docgenerator:4.0.27-SNAPSHOT')
    add('documentation', 'org.apache.groovy:groovy-templates:4.0.27-SNAPSHOT')
}

ext {
    includeInApiDocs = true
}

tasks.named('groovydoc', Groovydoc) {
    classpath = configurations.documentation
    groovyClasspath = configurations.documentation
    access = GroovydocAccess.PROTECTED
    includeAuthor = true
    includeMainForScripts = false
    processScripts = false
    destinationDir = project.file('build/docs/api')
}

tasks.named('javadoc', Javadoc) {
    enabled = false
}

tasks.named('javadocJar', Jar) {
    reproducibleFileOrder = true
    preserveFileTimestamps = false
    dirMode = 0755 // To avoid platform specific defaults
    fileMode = 0644 // to avoid platform specific defaults

    dependsOn('groovydoc')

    // Ensure the java source set is included in the groovydoc source set
    SourceSetContainer sourceSets = extensions.getByType(SourceSetContainer)
    def groovydocTask = tasks.named('groovydoc', Groovydoc).get()
    groovydocTask.source(project.files(sourceSets.main.java.srcDirs))

    ConfigurableFileCollection groovyDocFiles = files(groovydocTask.destinationDir)
    from(groovyDocFiles)
    inputs.files(groovyDocFiles)
}
