/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

import org.gradle.api.internal.plugins.StartScriptGenerator
import org.gradle.api.internal.plugins.UnixStartScriptGenerator
import org.gradle.api.internal.plugins.WindowsStartScriptGenerator

tasks.register('collectCliDependencies') {
    doLast {
        def projectNames = subprojects*.name
        def seen = []
        project(':grails-shell-cli').configurations.runtimeClasspath.with {
            for (artifact in resolvedConfiguration.resolvedArtifacts) {
                if (artifact in seen) continue
                seen << artifact
                def dependency = artifact.moduleVersion.id
                if (!projectNames.contains(dependency.name)) {
                    syncCliDependencies.into("$dependency.group/$dependency.name/jars") {
                        from(artifact.file) // this will trigger the actual download if necessary
                    }
                }
            }
        }
    }
}

tasks.register('syncCliDependencies', Sync) {
    dependsOn(tasks.named('collectCliDependencies'))
    into(homeLibDir)
    includeEmptyDirs = false
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.register('grailsCreateStartScripts', GrailsCreateStartScripts) {
    description = 'Creates OS specific scripts to run grails-shell as a JVM application.'
    mainClass = 'org.grails.cli.GrailsCli'
    applicationName = 'grails'
    defaultJvmOpts = ['-XX:+TieredCompilation', '-XX:TieredStopAtLevel=1', '-XX:CICompilerCount=3']
    outputDir = rootProject.layout.projectDirectory.dir('bin').asFile
    classpath = rootProject.childProjects['grails-shell-cli'].configurations.runtimeClasspath
    projectArtifacts = rootProject.childProjects['grails-shell-cli'].tasks.named('jar').get().outputs.files.collect {
        "dist/$it.name"
    } as List<String>
    doLast {
        ant.replace(file: rootProject.layout.projectDirectory.file('bin/grails').asFile, token: 'media/gradle.icns', value: 'media/icons/grails.icns')
        ant.chmod(file: rootProject.layout.projectDirectory.file('bin/grails').asFile, perm: 'ugo+rx')
    }
}

class GrailsCreateStartScripts extends CreateStartScripts {

    @Input
    Collection<String> projectArtifacts = []

    @TaskAction
    void generate() {
        Project grailsShellProject = rootProject.childProjects['grails-shell-cli']
        def unixStartScriptGenerator = new UnixStartScriptGenerator()
        unixStartScriptGenerator.template = grailsShellProject.resources.text.fromFile('src/main/resources/unixStartScript.txt')
        def generator = new StartScriptGenerator(unixStartScriptGenerator, new WindowsStartScriptGenerator())
        generator.applicationName = applicationName
        generator.mainClassName = mainClass.get()
        generator.defaultJvmOpts = defaultJvmOpts
        generator.optsEnvironmentVar = optsEnvironmentVar
        generator.exitEnvironmentVar = exitEnvironmentVar
        generator.classpath = projectArtifacts + getClasspath().resolvedConfiguration.resolvedArtifacts.collect { artifact ->
            def dependency = artifact.moduleVersion.id
            String installedFile = "lib/$dependency.group/$dependency.name/jars/$artifact.file.name"
            if (dependency.group.startsWith('org.apache.grails') && !project.file(installedFile).exists()) {
                installedFile = "dist/$artifact.file.name"
            }
            installedFile
        }
        generator.scriptRelPath = "bin/$unixScript.name"
        generator.generateUnixScript(unixScript)
        generator.generateWindowsScript(windowsScript)
    }
}

tasks.register('install') { Task installTask ->
    installTask.dependsOn('syncCliDependencies', 'grailsCreateStartScripts')
    subprojects {
        if (!(name in testProjects) && !(name in docProjects) && !(name in cliProjects) && !(name in profileProjects)) {
            installTask.dependsOn("$name:publishToMavenLocal")
        }
    }
}

tasks.register('assemble', Zip) {
    dependsOn('install')
    group = 'build'
    destinationDirectory = rootProject.layout.buildDirectory.dir('distributions')
    archiveBaseName = 'grails'
    archiveAppendix = grailsVersion

    exclude('**/CVS/**')

    into("grails-$grailsVersion") {
        from(rootProject.layout.projectDirectory) {
            // Some of these are probably not needed as they are not present in the project folder
            include('bin/grails', 'bin/grails.bat', 'lib/', 'media/', 'samples/', 'scripts/', 'LICENSE', 'INSTALL')

            def pathsToExclude = ['ant/bin', 'src/grails', 'src/war']
            docProjects.each { projectName ->
                pathsToExclude << rootProject.projectDir.relativePath(project(projectName as String).projectDir)
            }
            testProjects.each { projectName ->
                pathsToExclude << rootProject.projectDir.relativePath(project(projectName as String).projectDir)
            }
            cliProjects.each { projectName ->
                pathsToExclude << rootProject.projectDir.relativePath(project(projectName as String).projectDir)
            }
            exclude(pathsToExclude)
        }
        from(homeDistDir) {
            into('dist')
            exclude('*.zip')
        }
    }
}