/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

import org.asciidoctor.gradle.jvm.AsciidoctorTask

buildscript {
    apply from: rootProject.layout.projectDirectory.file('dependencies.gradle')
}

plugins {
    id 'groovy'
    id 'org.asciidoctor.jvm.convert'
}

version = projectVersion

ext {
    coreProjects = ['grails-datastore-core', 'grails-datamapping-core']
}

apply plugin: 'org.apache.grails.buildsrc.groovydoc'

dependencies {
    documentation platform(project(':grails-neo4j-bom'))
    documentation 'org.apache.groovy:groovy'
    documentation 'org.apache.groovy:groovy-ant'
    documentation 'org.apache.groovy:groovy-groovydoc'
    documentation 'org.apache.groovy:groovy-templates'
    documentation 'org.apache.groovy:groovy-dateutil'
    documentation 'com.github.javaparser:javaparser-core'
    coreProjects.each {
        documentation "org.apache.grails.data:$it"
    }
    rootProject.subprojects
            .findAll { it.findProperty('gormApiDocs') }
            .each {
                // TODO: This needs fixed for hibernate 7, but with the hibernate version conflicts, we may need to do separate documentation publishing
                if (!it.name.startsWith('grails-data-hibernate7')) {
                    documentation project(":$it.name")
                }
            }
}

tasks.named('asciidoctor', AsciidoctorTask) { AsciidoctorTask it ->
    it.inputs.dir(project.layout.projectDirectory.dir('src/docs/asciidoc')).withPropertyName('docsSrcDir').withPathSensitivity(PathSensitivity.RELATIVE)
    it.outputs.dir layout.buildDirectory.dir('asciidoc/manual')

    it.jvm {
        jvmArgs("--add-opens", "java.base/sun.nio.ch=ALL-UNNAMED", "--add-opens", "java.base/java.io=ALL-UNNAMED")
    }
    it.baseDirFollowsSourceFile()
    it.sourceDir layout.projectDirectory.dir('src/docs/asciidoc')
    it.outputDir = layout.buildDirectory.dir('asciidoc/manual')
    it.attributes = [
            'experimental' : 'true',
            'compat-mode'  : 'true',
            'toc'          : 'left',
            'icons'        : 'font',
            'reproducible' : '',
            'version'      : projectVersion,
            'pluginVersion': projectVersion,
            'neo4jVersion' : combinedVersions['neo4j-harness.version'],
            'exampledir'   : rootProject.findProject(':grails-test-examples-neo4j-base').layout.projectDirectory.asFile.absolutePath,
            'testsdir'     : rootProject.findProject(':grails-data-neo4j-core').layout.projectDirectory.dir('src/test/groovy').asFile.absolutePath
    ]
}

tasks.withType(Groovydoc).configureEach { Groovydoc groovydoc ->
    groovydoc.dependsOn(rootProject.subprojects
            .findAll { it.findProperty('gormApiDocs') }
            .collect { ":${it.name}:groovydoc" })
    groovydoc.docTitle = "GORM for Neo4j - $project.version"
    groovydoc.includeAuthor = true

    def sourceFiles = coreProjects.collect {
        layout.projectDirectory.files("$it/src/main/groovy")
    }.sum()

    rootProject.subprojects
            .findAll { it.findProperty('gormApiDocs') }
            .each { sourceFiles += it.files('src/main/groovy') }

    groovydoc.source = sourceFiles
    groovydoc.destinationDir = layout.buildDirectory.dir('combined-api/api').get().asFile
    groovydoc.classpath = configurations.documentation

    List<File> groovydocSrcDirs = coreProjects.collect {
        layout.projectDirectory.dir("$it/src/main/groovy").asFile
    }
    rootProject.subprojects
            .findAll { sp -> sp.findProperty('gormApiDocs') }
            .each { sp -> groovydocSrcDirs << new File(sp.projectDir, 'src/main/groovy') }
    groovydoc.ext.groovydocSourceDirs = groovydocSrcDirs
}

tasks.register('docs', Sync).configure { Sync docTask ->
    docTask.group = 'documentation'
    docTask.dependsOn('asciidoctor', 'groovydoc')

    def apiDir = layout.buildDirectory.dir('combined-api')
    def resourceDir = layout.projectDirectory.dir('src/docs/resources')
    def guideDir = layout.buildDirectory.dir('asciidoc')

    docTask.from apiDir, resourceDir, guideDir
    docTask.into layout.buildDirectory.dir('docs')

    docTask.finalizedBy('assembleDocsDist')
}

tasks.register('assembleDocsDist', Zip).configure { Zip it ->
    it.dependsOn('docs')
    it.from(layout.buildDirectory.dir('docs'))
    it.archiveFileName = "${project.name}-${project.version}.zip"
    it.destinationDirectory = project.layout.buildDirectory.dir('distributions')
}

// the groovy plugin is applied to this project, but we do not build a jar file since
// the dependencies are only used for resolving versions from the bom
tasks.withType(Jar).configureEach {
    enabled = false
}
