/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package grails.gorm.tests.inheritance

import groovy.sql.Sql

import grails.gorm.annotation.Entity
import org.grails.datastore.mapping.core.DatastoreUtils
import org.grails.orm.hibernate.HibernateDatastore
import org.grails.orm.hibernate.cfg.Settings
import spock.lang.Issue
import spock.lang.Specification

@Issue('https://github.com/apache/grails-core/issues/16465')
class TablePerHierarchyDefaultDiscriminatorSpec extends Specification {

    void "a hierarchy without a discriminator mapping stores the fully qualified class name in a class column"() {
        given:
        String url = 'jdbc:h2:mem:tphDefaultDiscriminator;DB_CLOSE_DELAY=-1'
        HibernateDatastore datastore = createDatastore(url, 'create-drop', DiscVehicle, DiscCar, DiscSportsCar)
        Sql sql = Sql.newInstance(url, 'sa', '')

        when:
        DiscVehicle.withNewTransaction {
            new DiscVehicle(name: 'bike').save(failOnError: true)
            new DiscCar(name: 'sedan').save(failOnError: true)
            new DiscSportsCar(name: 'roadster').save(failOnError: true)
        }

        then:
        sql.rows('select "CLASS", name from disc_vehicle order by name').collectEntries { [it.name, it.CLASS] } == [
                bike    : DiscVehicle.name,
                roadster: DiscSportsCar.name,
                sedan   : DiscCar.name
        ]

        and:
        DiscVehicle.withNewTransaction {
            DiscVehicle.list(sort: 'name')*.getClass()
        } == [DiscVehicle, DiscSportsCar, DiscCar]

        cleanup:
        sql?.close()
        datastore?.close()
    }

    void "a hierarchy without a discriminator mapping validates against and reads a grails-data-hibernate5 schema"() {
        given:
        String url = 'jdbc:h2:mem:tphLegacyDiscriminator;DB_CLOSE_DELAY=-1'
        Sql sql = Sql.newInstance(url, 'sa', '')
        sql.execute('''
            create table legacy_vehicle (
                id bigint generated by default as identity,
                version bigint not null,
                name varchar(255) not null,
                "CLASS" varchar(255) not null,
                primary key (id)
            )
        ''')
        sql.executeInsert('insert into legacy_vehicle (version, name, "CLASS") values (0, ?, ?)', ['bike', LegacyVehicle.name])
        sql.executeInsert('insert into legacy_vehicle (version, name, "CLASS") values (0, ?, ?)', ['sedan', LegacyCar.name])

        when:
        HibernateDatastore datastore = createDatastore(url, 'validate', LegacyVehicle, LegacyCar)

        then:
        LegacyVehicle.withNewTransaction {
            LegacyVehicle.list(sort: 'name').collect { [it.getClass(), it.name] }
        } == [[LegacyVehicle, 'bike'], [LegacyCar, 'sedan']]

        cleanup:
        sql?.close()
        datastore?.close()
    }

    void "a root mapping that names only the discriminator column keeps the fully qualified class names as values"() {
        given:
        String url = 'jdbc:h2:mem:tphColumnOnlyDiscriminator;DB_CLOSE_DELAY=-1'
        HibernateDatastore datastore = createDatastore(url, 'create-drop', KindVehicle, KindCar)
        Sql sql = Sql.newInstance(url, 'sa', '')

        when:
        KindVehicle.withNewTransaction {
            new KindVehicle(name: 'bike').save(failOnError: true)
            new KindCar(name: 'sedan').save(failOnError: true)
        }

        then:
        sql.rows('select kind, name from kind_vehicle order by name').collectEntries { [it.name, it.KIND] } == [
                bike : KindVehicle.name,
                sedan: KindCar.name
        ]

        and:
        KindVehicle.withNewTransaction {
            KindVehicle.list(sort: 'name')*.getClass()
        } == [KindVehicle, KindCar]

        cleanup:
        sql?.close()
        datastore?.close()
    }

    void "a table created by 8.0.0-RC1 or RC2 validates and reads with the documented mapping"() {
        given:
        String url = 'jdbc:h2:mem:tphReleaseCandidateDiscriminator;DB_CLOSE_DELAY=-1'
        Sql sql = Sql.newInstance(url, 'sa', '')
        sql.execute('''
            create table rc_vehicle (
                id bigint generated by default as identity,
                version bigint not null,
                name varchar(255) not null,
                dtype varchar(255) not null,
                primary key (id)
            )
        ''')
        sql.executeInsert('insert into rc_vehicle (version, name, dtype) values (0, ?, ?)', ['bike', RcVehicle.name])
        sql.executeInsert('insert into rc_vehicle (version, name, dtype) values (0, ?, ?)', ['sedan', 'RcCar'])
        sql.executeInsert('insert into rc_vehicle (version, name, dtype) values (0, ?, ?)', ['roadster', 'RcSportsCar'])

        when:
        HibernateDatastore datastore = createDatastore(url, 'validate', RcVehicle, RcCar, RcSportsCar)

        then:
        RcVehicle.withNewTransaction {
            RcVehicle.list(sort: 'name').collect { [it.getClass(), it.name] }
        } == [[RcVehicle, 'bike'], [RcSportsCar, 'roadster'], [RcCar, 'sedan']]

        when:
        RcVehicle.withNewTransaction {
            new RcVehicle(name: 'scooter').save(failOnError: true)
            new RcCar(name: 'wagon').save(failOnError: true)
        }

        then:
        sql.rows("select dtype, name from rc_vehicle where name in ('scooter', 'wagon') order by name").collectEntries { [it.name, it.DTYPE] } == [
                scooter: RcVehicle.name,
                wagon  : 'RcCar'
        ]

        cleanup:
        sql?.close()
        datastore?.close()
    }

    private static HibernateDatastore createDatastore(String url, String dbCreate, Class... classes) {
        new HibernateDatastore(
                DatastoreUtils.createPropertyResolver(
                        (Settings.SETTING_DB_CREATE): dbCreate,
                        'dataSource.url': url,
                        'dataSource.username': 'sa',
                        'dataSource.password': ''
                ),
                classes
        )
    }
}

@Entity
class DiscVehicle {
    String name
}

@Entity
class DiscCar extends DiscVehicle {
}

@Entity
class DiscSportsCar extends DiscCar {
}

@Entity
class LegacyVehicle {
    String name
}

@Entity
class LegacyCar extends LegacyVehicle {
}

@Entity
class KindVehicle {
    String name

    static mapping = {
        discriminator column: 'kind'
    }
}

@Entity
class KindCar extends KindVehicle {
}

@Entity
class RcVehicle {
    String name

    static mapping = {
        discriminator column: 'DTYPE'
    }
}

@Entity
class RcCar extends RcVehicle {
    static mapping = {
        discriminator 'RcCar'
    }
}

@Entity
class RcSportsCar extends RcCar {
    static mapping = {
        discriminator 'RcSportsCar'
    }
}
