/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

import org.apache.grails.gradle.tasks.bom.ExtractDependenciesTask
import org.apache.grails.gradle.tasks.bom.ExtractedDependencyConstraint
import org.apache.grails.gradle.tasks.bom.PropertyNameCalculator

buildscript {
    apply from: rootProject.layout.projectDirectory.file('dependencies.gradle')
}

plugins {
    id 'java-platform'
    id 'maven-publish'
}

version = projectVersion
group = 'org.apache.grails'

javaPlatform {
    allowDependencies()
}

ext {
    isReleaseBuild = System.getenv('GRAILS_PUBLISH_RELEASE') == 'true'
    isPublishedExternal = System.getenv().containsKey('NEXUS_PUBLISH_STAGING_PROFILE_ID')
}

dependencies {
    api platform(gradleBomPlatformDependencies['spring-boot-bom']), {
        exclude group: 'org.apache.groovy'
        exclude group: 'org.spockframework'
        exclude group: 'com.fasterxml.jackson'
    }

    for (def entry : bomPlatformDependencies.entrySet()) {
        api platform(entry.value)
    }

    constraints {
        for (def entry : gradleBomDependencies.entrySet()) {
            add('api', entry.value)
        }
        for (def entry : bomDependencies.entrySet()) {
            add('api', entry.value)
        }

        for (Project subproject : rootProject.subprojects) {
            if (subproject.path == project.path || subproject.name in testProjects || subproject.name in docProjects || subproject.name in cliProjects) {
                continue // ignore self & test projects
            }
            add('api', project(":$subproject.path"))
        }

        // since we're duplicating the bom instead of inheriting we have to add the grails-gradle projects
        // TODO: It should be possible to pull these build names using includedBuild, but I haven't found a way to do so
        add('api', "org.apache.grails:grails-gradle-plugins:$projectVersion")
        add('api', "org.apache.grails.gradle:grails-gradle-model:$projectVersion")
        add('api', "org.apache.grails:grails-docs-core:$projectVersion")

        // because we are not yet publishing hibernate6, just force the hibernate5 version for now
        add('api', 'org.liquibase:liquibase-core') {
            version {
                strictly(liquibaseHibernate5Version)
            }
        }
        add('api', 'org.liquibase.ext:liquibase-hibernate5') {
            version {
                strictly(liquibaseHibernate5Version)
            }
        }
    }
}

configurations.register('bomDependencies') {
    canBeResolved = true
    transitive = true
    extendsFrom(configurations.named('api').get())
}

tasks.register('extractConstraints', ExtractDependenciesTask) {
    configuration = configurations.named('bomDependencies')
    configurationName = 'bomDependencies'
    destination = layout.buildDirectory.file('grails-bom-constraints.adoc')
    platformDefinitions = combinedPlatforms
    definitions = combinedDependencies
    versions = combinedVersions
    dependsOn(
            tasks.named('generateMetadataFileForMavenPublication'),
            tasks.named('generatePomFileForMavenPublication')
    )
}

tasks.register('validateNoSnapshotDependencies') {
    doLast {
        configurations.each {
            it.allDependencies.each {
                if (it.version && it.version.contains('-SNAPSHOT')) {
                    throw new GradleException("Releases cannot have a snapshot dependency: $it.group:$it.name ($it.version)")
                }
            }
        }
    }
}

if (ext.isReleaseBuild && ext.isPublishedExternal) {
    tasks.named('generateMetadataFileForMavenPublication') {
        dependsOn(tasks.named('validateNoSnapshotDependencies'))
    }
    tasks.named('generatePomFileForMavenPublication') {
        dependsOn(tasks.named('validateNoSnapshotDependencies'))
    }
}

ext {
    pomDescription = 'Grails BOM (Bill of Materials) for managing dependency versions used by Grails Projects'
    pomCustomization = { ->
        def root = asNode()

        def propertiesNode = root.properties ? root.properties[0] : root.appendNode('properties')

        def depMgmt = root.dependencyManagement?.getAt(0)
        def deps = depMgmt?.dependencies?.getAt(0)
        if (deps) {
            Map<String, String> pomProperties = [:]
            deps.dependency.each { dep ->
                String groupId = dep.groupId.text().trim()
                String artifactId = dep.artifactId.text().trim()
                boolean isBom = dep.scope.text().trim() == 'import'

                String inlineVersion = dep.version.text().trim()
                if (inlineVersion == 'null') {
                    inlineVersion = null
                }

                PropertyNameCalculator propertyNameCalculator = new PropertyNameCalculator(combinedPlatforms, combinedDependencies, combinedVersions)
                if (inlineVersion) {
                    ExtractedDependencyConstraint extractedConstraint = propertyNameCalculator.calculate(groupId, artifactId, inlineVersion, isBom)
                    if (extractedConstraint?.versionPropertyReference) {
                        // use the property reference instead of the hard coded version so that it can be
                        // overriden by the spring boot dependency management plugin
                        dep.version[0].value = extractedConstraint.versionPropertyReference

                        // Add an entry in the <properties> node with the actual version number
                        pomProperties.put(extractedConstraint.versionPropertyName, inlineVersion)
                    }
                } else if (!inlineVersion) {
                    throw new GradleException("Dependency $groupId:$artifactId does not have a version.")
                }
            }

            for (Map.Entry<String, String> property : pomProperties.entrySet()) {
                propertiesNode.appendNode(property.key, property.value)
            }
        }
    }
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/publish-config.gradle')
}

// Workaround for https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/164
pluginManager.withPlugin('maven-publish') {
    publishing {
        repositories {
            maven {
                name = 'localBom'
                url = layout.buildDirectory.dir('repo')
            }
        }
    }
}