micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - https://grails.github.io
            - ${CORS_ALLOWED_ORIGIN:'https://start.grails.org'}
            - ${CORS_ALLOWED_ORIGIN_APACHE:'https://grails.apache.org'}
          allowedMethods:
            - GET
grails:
  forge:
    redirect-url: ${GITHUB_REDIRECT_URL:'https://start.grails.org/'}
gcp:
  http:
    client:
      auth:
        patterns:
          - /analytics/**
jackson:
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
  deserialization:
    READ_UNKNOWN_ENUM_VALUES_AS_NULL: true