/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.apache.grails.buildsrc

import javax.inject.Inject

import groovy.transform.CompileStatic

import org.gradle.api.file.FileCollection
import org.gradle.process.ExecOperations

/**
 * Runs groovydoc in a JVM of its own.
 *
 * <p>Groovydoc holds a model of every parsed class until the last page is written, and the
 * Groovy runtime behind it keeps unbounded parser caches for the life of the classloader that
 * loaded it. Run inside the Gradle daemon - which is where an Ant {@code taskdef} put it -
 * that cost is never given back: a build that documents every module ends up holding a
 * separate Groovy runtime per module and exhausts the daemon heap, taking whatever runs next
 * down with it.</p>
 *
 * <p>A forked JVM also solves a second problem. The Gradle daemon, and a Gradle worker
 * process with it, runs build logic on the Groovy that Gradle embeds, which is a major
 * version behind the one the framework is built with and wins every classloader lookup the
 * Ant task makes. Here the framework's Groovy is the only one present.</p>
 */
@CompileStatic
abstract class GroovydocRunner {

    private static final String SCRIPT_NAME = 'groovydoc-runner.groovy'

    @Inject
    abstract ExecOperations getExecOperations()

    /**
     * @param classpath the groovydoc tooling and the documented module's own classpath
     * @param workingDir a directory this run may write its parameter and script files to
     * @param verbose whether the forked Ant prints its own INFO messages
     */
    void run(FileCollection classpath, String maxHeapSize, File workingDir,
             Map<String, String> antArgs, List<Map<String, String>> links, boolean verbose) {
        workingDir.mkdirs()

        File scriptFile = new File(workingDir, SCRIPT_NAME)
        InputStream script = GroovydocRunner.getResourceAsStream(SCRIPT_NAME)
        if (script == null) {
            throw new IllegalStateException("${SCRIPT_NAME} is missing from the plugin classpath")
        }
        script.withStream { input ->
            scriptFile.withOutputStream { output -> output << input }
        }

        Properties params = new Properties()
        params.setProperty('verbose', String.valueOf(verbose))
        antArgs.each { String name, String value -> params.setProperty("arg.${name}".toString(), value) }
        links.eachWithIndex { Map<String, String> link, int index ->
            params.setProperty("link.${index}.packages".toString(), link.get('packages'))
            params.setProperty("link.${index}.href".toString(), link.get('href'))
        }

        File paramsFile = new File(workingDir, 'groovydoc-params.properties')
        paramsFile.withOutputStream { output ->
            params.store(output, 'Generated by GroovydocEnhancerPlugin')
        }

        execOperations.javaexec { spec ->
            spec.classpath = classpath
            spec.mainClass.set('groovy.ui.GroovyMain')
            spec.args = [scriptFile.absolutePath, paramsFile.absolutePath]
            spec.maxHeapSize = maxHeapSize
        }
    }
}
