/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

plugins {
    id 'groovy'
    id 'java-library'
    id 'project-report'
    id 'org.apache.grails.buildsrc.properties'
    id 'org.apache.grails.buildsrc.dependency-validator'
    id 'org.apache.grails.buildsrc.compile'
    id 'org.apache.grails.buildsrc.publish'
    id 'org.apache.grails.buildsrc.sbom'
    id 'org.apache.grails.buildsrc.vulnerability-scan'
    id 'org.apache.grails.gradle.grails-code-style'
    id 'org.apache.grails.gradle.grails-plugin'
    id 'org.apache.grails.gradle.grails-gsp'
}

version = projectVersion
group = 'org.apache.grails'

dependencies {

    implementation platform(project(':grails-bom'))

    api 'redis.clients:jedis', {
        // api: Jedis, JedisConnectionException
        // impl: JedisPool, JedisPoolConfig, JedisSentinelPool, Pipeline, Protocol, Transaction
    }
    api 'com.google.code.gson:gson', {
        // api: Gson (used by the @MemoizeObject AST transform)
    }

    implementation project(':grails-datamapping-core'), {
        // impl: @Transactional(runtime)
    }

    compileOnly project(':grails-core'), { // Provided as this is a Grails plugin
        // api: GrailsApplication, GrailsAutoConfiguration, Plugin, @PluginSource, Holders
    }
    compileOnly project(':grails-common'), {
        // comp: GroovyTransformOrder (AST transform ordering)
    }
    compileOnly project(':grails-web-gsp-taglib'), {
        // comp: TagLib artefact (RedisTagLib)
    }
    compileOnly 'org.apache.groovy:groovy' // Provided as this is a Grails plugin (AST transforms)
    compileOnly 'org.springframework:spring-beans' // @Autowired
    compileOnly 'org.springframework:spring-core' // org.springframework.asm.Opcodes
    compileOnly 'org.slf4j:slf4j-api' // @Slf4j
    compileOnly 'org.slf4j:slf4j-nop' // Remove warning about missing slf4j implementation during gsp compilation

    integrationTestImplementation project(':grails-testing-support-redis')
    integrationTestImplementation project(':grails-testing-support-web')
    integrationTestImplementation project(':grails-testing-support-datamapping')
    integrationTestImplementation 'org.spockframework:spock-core'

    integrationTestRuntimeOnly 'net.bytebuddy:byte-buddy'
}

apply {
    from rootProject.layout.projectDirectory.file('gradle/docs-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/grails-extension-gradle-config.gradle')
    from rootProject.layout.projectDirectory.file('gradle/redis-test-config.gradle')
}
