/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    https://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */

import grails.doc.AddReleaseDropDown
import grails.doc.gradle.PublishGuide
import org.asciidoctor.gradle.jvm.AsciidoctorTask

plugins {
    id 'base'
    id 'org.asciidoctor.jvm.convert'
    id 'groovy'
}

// Make sure doc projects are evaluated last so they pick up all projects with documentation since they are dynamically
// found by the aggregateGroovydoc task
rootProject.subprojects
        .findAll { !(it.name in testProjects) && it.name != project.name && !(it.name in cliProjects) && !(it.name in profileProjects) }
        .each { project.evaluationDependsOn(it.path) }

compileJava.options.release = javaVersion.toInteger()

version = projectVersion

ext {
    grailsCheckOutDir = layout.buildDirectory.dir('grails-core/checkout').get().asFile.absolutePath
    grailsTestsCheckOutDir = layout.buildDirectory.dir('grails-functional-tests/checkout').get().asFile.absolutePath
    outputDir = layout.buildDirectory.file('docs').get().asFile.absolutePath
    githubBranch = findProperty('githubBranch')
    guidePage = '/docs/guide/single.html'
    indexPage = '/docs/index.html'
}

dependencies {
    implementation platform(project(':grails-bom'))
    implementation 'org.apache.grails:grails-docs-core'
    implementation 'org.apache.groovy:groovy'

    // Used to surface versions for groovydoc
    implementation project(':grails-dependencies')
    implementation project(':grails-testing-support-core')
    implementation project(':grails-data-hibernate5')
    implementation 'org.apache.grails:grails-gradle-plugins'
    implementation 'org.testcontainers:testcontainers'
    implementation 'org.springframework:spring-core'
    implementation 'org.springframework.boot:spring-boot'
    implementation 'org.gebish:geb-spock'
}

// this task needs to be here instead of the root since bom resolution only occurs when the java / groovy plugins are applied
apply from: rootProject.layout.projectDirectory.file('gradle/docs-dependencies.gradle')
tasks.register('aggregateGroovydoc', Groovydoc) {
    group = 'documentation'
    def sources = rootProject.subprojects
            .findAll { it.findProperty('includeInApiDocs') }
            .collectMany {
                List possibleSources = [it.sourceSets.main]

                def testFixturesSource = it.sourceSets.findByName('testFixtures')
                if (testFixturesSource) {
                    possibleSources.add(testFixturesSource)
                }

                def astSource = it.sourceSets.findByName('ast')
                if (astSource) {
                    possibleSources.add(astSource)
                }
                possibleSources
            }
            .flatten() as List<SourceSet>
    source((sources.collect { [it.allSource.srcDirs, it.allSource.srcDirs] }.flatten() as List<File>).findAll {
        it.name in ['java', 'groovy'] && it.exists()
    }.unique())
    exclude('META-INF/**', '*yml', '*properties', '*xml', '**/Application.groovy', '**/Bootstrap.groovy', '**/resources.groovy')
    classpath = files(sources.collect { it.compileClasspath.filter(File.&isDirectory) }.flatten().unique())
    groovyClasspath = configurations.documentation
    destinationDir = project.layout.buildDirectory.dir('combined-api/api').get().asFile
    windowTitle = "Grails $projectVersion"
    docTitle = "Grails $projectVersion"
    access = GroovydocAccess.PROTECTED
    includeAuthor = true
    includeMainForScripts = false
    processScripts = false
    inputs.files(source)
    outputs.dir(destinationDir)

    def gebVersion = getVersion('geb-spock')
    def testContainersVersion = getVersion('testcontainers')
    def springVersion = getVersion('spring-core')
    def springBootVersion = getVersion('spring-boot')

    link("https://www.gebish.org/manual/$gebVersion/api/", 'geb.')
    link("https://javadoc.io/doc/org.testcontainers/testcontainers/$testContainersVersion/", 'org.testcontainers.')
    link("https://docs.spring.io/spring-framework/docs/$springVersion/javadoc-api/", 'org.springframework.core.')
    link("https://docs.spring.io/spring-boot/docs/$springBootVersion/api/", 'org.springframework.boot.')

    doLast {
        delete(layout.buildDirectory.dir('tmp'))
    }
}

// use jsoup in PdfBuilder for cleaning input html
System.setProperty('grails.docs.clean.html', 'true')
// creates single.html.before.xml and single.html.after.xml files for debugging pdf input when enabled
//System.setProperty('grails.docs.debug.pdf','true')

tasks.named('asciidoctor', AsciidoctorTask) {
    resources {
        from('resources')
    }
    options(template_dirs: ["$projectDir/src/docs/templates"])
    attributes(
            'experimental': 'true',
            'compat-mode':  'true',
            'icons':        'font',
            'linkcss':      'true',
            'docinfo1':     '',
            'toc':          'left',
            'version':      version,
            'sourcedir':    rootProject.projectDir.absolutePath
    )
    dependsOn('aggregateGroovydoc')
}

tasks.register('dist', Zip) {
    dependsOn('docs')
    from(outputDir)
}

tasks.register('createReleaseDropdown', AddReleaseDropDown) {
    group = 'documentation'
    dependsOn('publishGuide')

    inputFiles = layout.buildDirectory.files('original-guide/guide/single.html')
    docsDirectory = layout.buildDirectory.dir('original-guide')
    outputDir = layout.buildDirectory.dir('modified-guide')
}

tasks.register('resolveGroovyVersion') {
    group = 'documentation'
    description = 'Resolve Groovy Version from the BOM'
    ext.resolved = configurations.compileClasspath
            .resolvedConfiguration
            .resolvedArtifacts
            .find {
                it.moduleVersion.id.group == 'org.apache.groovy' &&
                        it.moduleVersion.id.name.contains('groovy')
            }.moduleVersion.id.version
    logger.lifecycle('Resolved Groovy version for Guide links: {}', ext.resolved as String)
}

String getVersion(String artifact) {
    String version = configurations.runtimeClasspath
            .resolvedConfiguration
            .resolvedArtifacts
            .find {
                it.moduleVersion.id.name == artifact
            }?.moduleVersion?.id?.version
    if (!version) {
        throw new GradleException("Could not find $artifact version.")
    }
    return version
}

tasks.register('publishGuide', PublishGuide) {
    dependsOn('generateBomDocumentation', 'aggregateGroovydoc', 'jar', 'resolveGroovyVersion', 'processTestResources', 'compileTestJava', 'compileTestGroovy', 'test')

    // No language setting because we want the English guide to be
    // generated with a 'en' in the path, but the source is in 'en'
    // so that it's easy to track with git.
    targetDir = layout.buildDirectory.dir('original-guide')
    sourceRepo = "https://github.com/apache/grails-core/edit/$githubBranch/grails-doc/src/en"
    sourceDir = layout.projectDirectory.dir('src/en')
    propertiesFiles = files(
            rootProject.layout.projectDirectory.file('gradle.properties')
    )

    properties = provider {
        def springVersion = getVersion('spring-core')
        def springBootVersion = getVersion('spring-boot')
        [
                'api'                      : '../api',
                'safe'                     : 'UNSAFE', // Make sure any asciidoc security is disabled
                'jakartaee'                : 'https://jakarta.ee/specifications/platform/10/apidocs/',
                'javase'                   : "https://docs.oracle.com/en/java/javase/$javaVersion/docs/api/",
                'groovyapi'                : "https://docs.groovy-lang.org/$resolveGroovyVersion.resolved/html/gapi/",
                'groovyjdk'                : "https://docs.groovy-lang.org/$resolveGroovyVersion.resolved/html/groovy-jdk/",
                'groovyVersion'            : resolveGroovyVersion.resolved,
                'springapi'                : "https://docs.spring.io/spring/docs/$springVersion/javadoc-api/",
                'springdocs'               : "https://docs.spring.io/spring/docs/$springVersion/",
                'githubBranch'             : githubBranch,
                'gormApiDocs'              : '../grails-data/api',
                'gormWebsite'              : '../grails-data',
                'hibernate5Guide'          : '../grails-data/hibernate5',
                'mongodb5Guide'            : '../grails-data/mongodb',
                'hibernate5Reference'      : 'https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html',
                'springapi'                : "https://docs.spring.io/spring/docs/$springVersion/javadoc-api/",
                'springbootapi'            : "https://docs.spring.io/spring-boot/docs/$springBootVersion/api",
                'springBootReference'      : "https://docs.spring.io/spring-boot/docs/$springBootVersion/reference",
                'springBootVersion'        : springBootVersion,
                'springVersion'            : springVersion,
                'gradleVersion'            : gradle.gradleVersion,
                'GrailsVersion'            : projectVersion,
                'version'                  : projectVersion,
                'gormVersion'              : projectVersion,
                'cacheExampleSourceDir'    : rootProject.layout.projectDirectory.dir('grails-test-examples/cache').asFile,
                'hibernate5Version'        : getVersion('hibernate-core-jakarta'),
                'spockVersion'             : getVersion('spock-core'),
                'testingSupportVersion'    : getVersion('grails-testing-support-core'),
                'grailsGradlePluginVersion': getVersion('grails-gradle-plugins'),
                'sourcedir'                : rootProject.layout.projectDirectory.asFile,
                'functionalSourceDir'      : rootProject.layout.projectDirectory.asFile,
                'gparsdocs'                : "https://gpars.org/$gparsVersion/groovydoc",
                'rxjavadocs'               : 'https://reactivex.io/RxJava/1.x/javadoc',
                'rxjava2docs'              : 'https://reactivex.io/RxJava/2.x/javadoc',
                'tags'                     : '../ref/Tags'
        ] as Map<String, String>
    }
}

tasks.register('generateBomDocumentation') {
    dependsOn(':grails-bom:extractConstraints')

    description = 'Generates an AsciiDoc table listing Group, Artifact, and Version for project dependencies.'
    group = 'documentation'

    inputs.files(project(':grails-bom').layout.projectDirectory.asFileTree)
    outputs.file(layout.projectDirectory.file('src/en/ref/Versions/Grails BOM.adoc'))

    doFirst {
        layout.projectDirectory.dir('src/en/ref/Versions').asFile.mkdirs()
    }

    doLast {
        def bomDocument = layout.projectDirectory.file('src/en/ref/Versions/Grails BOM.adoc').asFile
        bomDocument.withWriter { writer ->
            writer.writeLine '== Grails BOM Dependencies'
            writer.writeLine ''
            writer.writeLine 'This document provides information about the dependencies defined in the Grails BOM - also known as `org.apache.grails:grails-bom`. It includes the artifact coordinates, where in the hierarchy the coordinate was defined, and the maven property that defines the version.'
            writer.writeLine ''
            writer.write(project(':grails-bom').layout.buildDirectory.file('grails-bom-constraints.adoc').get().asFile.text)
            writer.writeLine ''
        }

        logger.lifecycle "BOM Dependency Page generated to: $bomDocument.absolutePath"
    }
}

tasks.register('generateGuide') {
    dependsOn('createReleaseDropdown')
    group = 'documentation'
}

tasks.register('docs', Sync) {
    dependsOn 'aggregateGroovydoc', 'generateGuide', ':grails-data-docs-stage:docs'
    group = 'documentation'

    def manualDocsDir = layout.buildDirectory.dir('modified-guide')
    def apiDocsDir = layout.buildDirectory.dir('combined-api')
    def dataDocsDir = rootProject.layout.projectDirectory.dir('grails-data-docs/stage/build/docs')

    def mergedDocsDir = layout.buildDirectory.dir('docs')

    inputs.dir(manualDocsDir)
    inputs.dir(apiDocsDir)
    inputs.dir(dataDocsDir)
    inputs.dir(layout.projectDirectory.dir('src'))

    outputs.dir(mergedDocsDir)

    from(manualDocsDir, apiDocsDir, dataDocsDir)
    into(mergedDocsDir)
}

artifacts {
    archives dist
}

// the groovy plugin is applied to this project, but we do not build a jar file since
// the dependencies are only used for resolving versions from the bom
tasks.withType(Jar).configureEach {
    enabled = false
}