# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Java CI"
on:
  push:
    branches:
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  pull_request:
    branches:
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  workflow_dispatch:
env:
  # To prevent throttling of GitHub API usage, include the GitHub token as an environment variable
  # as the build will use it when fetching git tags in CreateReleaseDropDown.groovy
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# queue jobs and only allow 1 run per branch due to the likelihood of hitting GitHub resource limits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  buildGradle:
    name: 'Build Gradle Plugins'
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🔨 Build project without tests"
        if: ${{ contains(github.event.head_commit.message, '[skip tests]') }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew build
          --continue --stacktrace -PskipTests
      - name: "🔨 Build project with tests"
        if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew build
          --continue --stacktrace
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    name: 'Build Grails-Core'
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 24 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🔨 Build project"
        run: >
          ./gradlew build :grails-shell-cli:installDist groovydoc
          --continue --stacktrace -PonlyCoreTests
  functional:
    name: "Functional Tests"
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21, 24 ]
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "🏃 Run Functional Tests"
        run: >
          ./gradlew bootJar check
          --continue --stacktrace
          -PonlyFunctionalTests
          -PskipHibernate5Tests
          -PskipMongodbTests
  mongodbFunctional:
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    name: "Mongodb Functional Tests"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
        mongodb-version: [ '7.0', '8.0' ] # test with supported versions https://www.mongodb.com/legal/support-policy/lifecycles
    steps:
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🏃 Run Functional Tests"
        env:
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./gradlew bootJar cleanTest check
          --continue --stacktrace
          -PonlyMongodbTests
          -PmongodbContainerVersion=${{ matrix.mongodb-version }}
  hibernate5Functional:
    if: ${{ !contains(github.event.head_commit.message, '[skip tests]') }}
    name: "Hibernate5 Functional Tests"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
    steps:
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🏃 Run Functional Tests"
        env:
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ./gradlew bootJar cleanTest check
          --continue --stacktrace
          -PonlyHibernate5Tests
  publishGradle:
    if: github.repository_owner == 'apache' && github.event_name == 'push'
    needs: [ buildGradle ]
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "📤 Publish Gradle Snapshot Artifacts"
        env:
          GRAILS_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        working-directory: 'grails-gradle'
        run: >
          ./gradlew publish
          -Dorg.gradle.internal.publish.checksums.insecure=true
  publish:
    needs: [ publishGradle, build, functional, hibernate5Functional, mongodbFunctional ]
    if: ${{ always() && github.repository_owner == 'apache' && github.event_name == 'push' && needs.publishGradle.result == 'success' && (needs.build.result == 'success' || needs.build.result == 'skipped') && (needs.functional.result == 'success' || needs.functional.result == 'skipped') && (needs.hibernate5Functional.result == 'success' || needs.hibernate5Functional.result == 'skipped') && (needs.mongodbFunctional.result == 'success' || needs.mongodbFunctional.result == 'skipped') }}
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: "📤 Publish Grails-Core Snapshot Artifacts"
        env:
          GRAILS_PUBLISH_RELEASE: 'false'
          MAVEN_PUBLISH_URL: ${{ secrets.GRAILS_NEXUS_PUBLISH_SNAPSHOT_URL }}
          MAVEN_PUBLISH_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PUBLISH_PASSWORD: ${{ secrets.NEXUS_PW  }}
        run: ./gradlew publish
      - name: "🔨 Create Grails Wrapper Distribution Zip"
        run: >
          ./gradlew :grails-wrapper:distZip
      - name: "✅ Verify grails-wrapper"
        if: success()
        run: |
          cp grails-wrapper/build/distributions/grails-wrapper-*.zip build/wrapper.zip
          cd build
          unzip wrapper -d tmp
          mv tmp/grails-wrapper-* tmp/wrapper
          ./tmp/wrapper/grailsw --version
      - name: "📤 Upload Wrapper Zip to Workflow Summary Page"
        uses: actions/upload-artifact@v4
        with:
          name: grails-wrapper-snapshot
          path: build/tmp/wrapper/
  docs:
    if: github.repository_owner == 'apache' && github.event_name == 'push'
    needs: [ publish ]
    runs-on: ubuntu-24.04
    steps:
      - name: "📥 Checkout the repository"
        uses: actions/checkout@v4
      - name: 'Ensure Common Build Date' # to ensure a reproducible build
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"
      - name: "🔀 Store current branch name"
        run: |
          TARGET_BRANCH="${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}"
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
          echo "Target Branch: ${TARGET_BRANCH}"
      - name: "📅 Set current date as env variable"
        run: |
          NOW=$(date +'%Y-%m-%dT%H%M%S')
          echo "NOW=${NOW}" >> $GITHUB_ENV
          echo "Current date: ${NOW}"
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY }}
      - name: "🔨 Build Snapshot Documentation"
        run: >
          ./gradlew grails-doc:build
          -PgithubBranch=${{ env.TARGET_BRANCH }}
      - name: "📤 Upload Generated Docs to Workflow Result Page"
        uses: actions/upload-artifact@v4
        with:
          name: grails-docs-${{ env.NOW }}.zip
          path: ./build/distributions/*.zip
          compression-level: 0 # Already a zip
      - name: "🚀 Publish to Github Pages"
        if: github.event_name == 'push'
        uses: apache/grails-github-actions/deploy-github-pages@asf
        env:
          GH_TOKEN: ${{ secrets.GRAILS_GHTOKEN }}
          GRADLE_PUBLISH_RELEASE: 'false'
          SOURCE_FOLDER: grails-doc/build/docs
          TARGET_REPOSITORY: 'apache/grails-doc'
